server:
  port: 42064
  # sessions
  servlet:
    session:
      timeout: 7d
spring:
  session:
    jdbc:
      initialize-schema: embedded
      table-name: sessions
  # database config
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: false
    hibernate.ddl-auto: update
  datasource:
    hikari:
      auto-commit: true
  # mvc config
  web:
    resources:
      static-locations: classpath:/static/
